"""init

Revision ID: 527567af9c39
Revises:
Create Date: 2021-05-21 11:51:07.687418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527567af9c39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("admin_user",
                    sa.Column("created_at", sa.DateTime(), nullable=True),
                    sa.Column("updated_at", sa.DateTime, nullable=True),
                    sa.Column("id", sa.String(64), nullable=False),
                    sa.Column("account", sa.String(64), nullable=False),
                    sa.Column("password", sa.String(128), nullable=False),
                    sa.Column("nickname", sa.String(64), nullable=False),
                    sa.Column("avatar", sa.String(125), nullable=True),
                    sa.Column("enabled", sa.Boolean(), server_default=sa.text("True"), nullable=True),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_index("idx_account", "admin_user", ["account"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_account", table_name="admin_user")
    op.drop_table("admin_user")
    # ### end Alembic commands ###
