"""add article table

Revision ID: edf3d6b195b4
Revises: 527567af9c39
Create Date: 2021-05-25 11:17:49.067188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edf3d6b195b4'
down_revision = '527567af9c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("article",
                    sa.Column("created_at", sa.DateTime(), nullable=True),
                    sa.Column("updated_at", sa.DateTime, nullable=True),
                    sa.Column("id", sa.String(32), nullable=False),
                    sa.Column("name", sa.String(125), nullable=False, comment="名称"),
                    sa.Column("introduction", sa.String(255), nullable=True, comment="简介"),
                    sa.Column("cover", sa.String(255), nullable=True, comment="封面"),
                    sa.Column("content", sa.TEXT(), nullable=False, comment="正文"),
                    sa.Column("views", sa.Integer(), nullable=False, default=0, comment="浏览量"),
                    sa.Column("likes", sa.Integer(), nullable=False, default=0, comment="点赞数"),
                    sa.Column("tags", sa.JSON, nullable=False, comment="标签"),
                    sa.Column("article_type", sa.Integer(), nullable=False, comment="类型：0原创，1转载"),
                    sa.Column(
                        "is_public", sa.Boolean(), server_default=sa.text("True"), nullable=True, comment="是否公开"),
                    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
                    sa.Column("deleted", sa.Boolean(), server_default=sa.text("False"), nullable=False),
                    sa.PrimaryKeyConstraint("id"),
                    sa.UniqueConstraint("name", "deleted_at", "deleted")
                    )
    op.create_table("comment",
                    sa.Column("created_at", sa.DateTime(), nullable=True),
                    sa.Column("updated_at", sa.DateTime, nullable=True),
                    sa.Column("id", sa.String(32), nullable=False),
                    sa.Column("content", sa.TEXT, nullable=False, comment="评论内容"),
                    sa.Column("likes", sa.Integer(), nullable=False, default=0, comment="点赞数"),
                    sa.Column("article_id", sa.String(32), nullable=False, comment="文章ID"),
                    sa.Column("pid", sa.String(32), nullable=False, default="0", comment="父级评论ID"),
                    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
                    sa.Column("deleted", sa.Boolean(), server_default=sa.text("False"), nullable=False),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_index("idx_article", "comment", ["article_id"], unique=False)
    op.create_index("idx_pid", "comment", ["pid"], unique=False)
    op.create_table("article_tag",
                    sa.Column("created_at", sa.DateTime(), nullable=True),
                    sa.Column("updated_at", sa.DateTime, nullable=True),
                    sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
                    sa.Column("name", sa.String(32), nullable=False, default="0", comment="分类名称"),
                    sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="删除时间"),
                    sa.Column("deleted", sa.Boolean(), server_default=sa.text("False"), nullable=False),
                    sa.PrimaryKeyConstraint("id")
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("article_tag")
    op.drop_index("idx_pid", table_name="comment")
    op.drop_index("idx_article", table_name="comment")
    op.drop_table("comment")
    op.drop_table("article")
    # ### end Alembic commands ###
